version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    bct_1:
      image: talcaniz/deep-oc-bct_1
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    bct_1-gpu:
      image: talcaniz/deep-oc-bct_1:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    bct_1-rclone:
      extends:
        service: bct_1
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
